name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the details below.

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear description of the bug.
      placeholder: Describe the unexpected behavior...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: How can we reproduce the issue?
      placeholder: |
        1. Start services with `docker compose up`
        2. Create a task with complexity 5
        3. Observe error in...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the system is affected?
      options:
        - UI (React frontend)
        - API (Express backend)
        - Agents (Python/CrewAI)
        - Ollama (local model)
        - Docker / Infrastructure
        - Task Routing
        - Other
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Your setup details
      placeholder: |
        - OS: Windows 11 / Ubuntu 22.04 / macOS
        - GPU: RTX 3060 Ti 8GB (or none)
        - Docker version: 24.x
        - RAM: 16GB
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      description: Paste any error logs, container logs, or browser console output.
      render: shell
    validations:
      required: false
