name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea to make ABCC better? We'd love to hear it!

  - type: textarea
    id: problem
    attributes:
      label: Problem or motivation
      description: What problem does this solve, or why would this be useful?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How do you think this should work?
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Area
      description: Which part of the system would this affect?
      options:
        - UI / UX
        - Task Routing / Complexity
        - Agent System
        - Ollama / Local Models
        - Claude API Integration
        - Cost Tracking
        - Audio / Voice Packs
        - Docker / Deployment
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: effort
    attributes:
      label: Estimated effort
      description: How big do you think this is?
      options:
        - Small (a few hours)
        - Medium (a few days)
        - Large (a week+)
        - Not sure
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any other approaches you thought about?
    validations:
      required: false
